version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  # Zookeeper (prérequis pour Kafka)
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  # Kafka Broker
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper

  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - auth-service
      - product-service
      - order-service
      - inventory-service
      - notification-service

  # Auth Service
  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MONGO_URI=mongodb://root:example@mongodb:27017/authdb
    depends_on:
      - mongodb

  # Product Service
  product-service:
    build:
      context: ./product-service
    container_name: product-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MONGO_URI=mongodb://root:example@mongodb:27017/productdb
    depends_on:
      - mongodb

  # Order Service
  order-service:
    build:
      context: ./order-service
    container_name: order-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MONGO_URI=mongodb://root:example@mongodb:27017/orderdb
    depends_on:
      - mongodb
      - kafka

  # Inventory Service
  inventory-service:
    build:
      context: ./inventory-service
    container_name: inventory-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MONGO_URI=mongodb://root:example@mongodb:27017/inventorydb
    depends_on:
      - mongodb
      - kafka

  # Notification Service
  notification-service:
    build:
      context: ./notification-service
    container_name: notification-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - kafka

  # Frontend (Vue.js)
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - VUE_APP_API_BASE_URL=http://localhost:8080
    depends_on:
      - api-gateway
